spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: ${ORDER_SERVICE_URL}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1