spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

user:
  service:
    base-url: ${CLIENT_USER_SERVICE_URL}